### ISSUE TITLE
Process does not exit on completion

### ISSUE THREAD

**Issue by heffergm** [pelias-deprecated/deprecated-quattroshapes#1]
When running bin/pelias-quattroshapes, the process does not exit on completion of the load, and all socket connections to the ES backend(s) remain established.

**Comment by missinglink** [comment]
You should still be using `https://github.com/pelias/quattroshapes-pipeline`, sorry I need to deprecate this repo.

add deprecation notices: https://github.com/mapzen/pelias-quattroshapes/commit/01501714ed60ce38e54ed06cb92a7c41b35b870d https://github.com/mapzen/pelias-quattroshapes/commit/a321cac622c0a1c203a94cac90cf974a45dc7bca
